### PR TITLE
Feature/hierarchical graphs

### PR DESCRIPTION
**Pull request by icedoom888**
An implementation of hierarchical graph structure.
This allows for the creation of multi-layered graph structures. It removes the need for long distance edges in the hidden representation.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-graphs?pullRequest=48) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-graphs?pullRequest=48) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/anemoi-graphs?pullRequest=48) it.</sub>

**Review by JPXKQX — COMMENTED** [review]
Hello Alberto! Very pleased to see your contribution to anemoi-graphs. My first question would be whether the resulting graphs could be generated on the current branch without any changes, just by writing [a longer config file](https://github.com/user-attachments/files/16992531/recipe_hierarchical.txt). 

Second, I really like the new plotting features, and it would be nice to have them in anemoi-graphs. I would suggest integrating this into the current design. For example, create 1 or 3 high level functions plot_hierarchical_diagram() (in interactive_html.py). This way this function can be used in Jupyter notebooks or in the CLI. There are also some new functions already implemented like lat_lon_to_cartesian (latlon_rad_to_cartesian in generate/transforms.py).

**Comment by icedoom888** [comment]
Hey Mario! Happy to collab on this with you :) 

To answer your questions:

1.  You are correct, you could write up the full config as you suggested. For future implementations though, I believe it would be useful to have a more modular implementation, that allows to make deeper networks without writing up each hidden layer manually. It makes the config more readable too. 

2. Yes I made some separate functions in `src/anemoi/graphs/plotting/graph_vis_funcs.py` but i can integrate them into `interactive_html.py`. The only issue in my experience is that these 3d interactive plots tend to not work properly on browsers. They work in Jupyter notebooks though.

**Comment by icedoom888** [comment]
Hey @JPXKQX! Got back working on this merge.
I have two questions:

- Did we find an agrement on the graph creators? Should it be indeed an extensible class?
- Regarding the plotting tools: I made a new branch and reformatted the functions as requested. Concerning the notebook showing how to use the functions, where should this be located?

**Pull request closed without merging**
