### PR TITLE
[feature] Stretched graphs

### PR DESCRIPTION
**Pull request by JPXKQX**
This PR implements the functionality to build stretched graphs only in an area of interest (AOI).

This includes: 
- The aoi_mask_builder objects is renamed to area_mask_builder.
- A new node builder, **StretchedTriNodes**, which allows to create a stretched graph.
- Expanding the **MultiScaleEdges** functionalities to support multi-scale connections in stretched graphs.

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the documentation and docstrings to reflect the changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have ensured that the code is still pip-installable after the changes and runs
- [ ] I have ran this on single GPU
- [ ] I have ran this on multi-GPU or multi-node

## Issue ticket number and link

Issues #8 

This work would not have been possible without @theissenhelen  and @JesperDramsch and the rest of the AIFS team! Thanks also to Magnus, Håvard and the MetNorway team for their contributions to this PR.

----
📚 Documentation preview 📚: https://anemoi-graphs--51.org.readthedocs.build/en/51/

### CODE REVIEW

**Comment by havardhhaugen** [comment]
Overall this looks really good, and we're pretty much able to reproduce the stretched grid graphs from the old graphgen in aifs-mono. I do have two suggestions:
- Add a keyword argument min_distance_km to CutOutZarrDatasetNodes so this can be set in the config (Or add functionality for passing any kwargs to CutOutZarrDatasetNodes through the config).
- Change how edge_length.invert works:
1) Currently the edge length normalization looks weird when used with invert; in the encoder / decoder I get edgelengths between [0.96,1] and in the processor some of them have negative edge weight. I'm guessing this happens because edgelengths are inverted before the call to super().post_process(values) in EdgeLenght.post_process().
2) Change the default value of invert to be True, giving shorter edges higher weight by default.

**Comment by JPXKQX** [comment]
Thanks for taking the time to review the PR. 
- The `CutOutZarrDatasetNodes` will be refactored to receive a dict-like argument `dataset` directly from the configuration file. This change will be merged in #52 . 
- We left `invert=False` as the default because we didn't see any difference (in performance). Regarding the difference between encoder/decoder and processor edge lengths, do you use the same `norm` in both cases? Would you expect to invert after normalisation?

**Comment by JPXKQX** [comment]
The issue should now be resolved. Invert is applied after normalization, and a new method called `"unit-range"` has been introduced to map values to the [0, 1] interval, as `"unit-max"` only scales by dividing by the maximum.

**Comment by havardhhaugen** [comment]
Great! The edge lengths with invert and unit max now look like what I would expect.

**Review by mchantry — APPROVED** [review]
LGTM, thanks very much.

**Pull request merged**
